apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0311at-pvc
  namespace: 0311at-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard 